version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 bus_project.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bus_project.settings
      - PYTHONUNBUFFERED=1
      - DJANGO_SECURE_SSL_REDIRECT=false
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app_network

volumes:
  postgres_data:
  static_volume:

networks:
  app_network:
    driver: bridge