# Generated by Django 5.2 on 2025-04-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bus_app", "0002_bus_passenger_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="available_seats",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="departure_time",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="fare",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="source",
        ),
        migrations.RemoveField(
            model_name="bus",
            name="total_seats",
        ),
        migrations.CreateModel(
            name="SeatClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_type",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Sleeper", "Sleeper"),
                            ("Luxury", "Luxury"),
                        ],
                        max_length=10,
                    ),
                ),
                ("total_seats", models.IntegerField()),
                ("available_seats", models.IntegerField()),
                ("fare", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_classes",
                        to="bus_app.bus",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="seat_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bus_app.seatclass",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("arrival_time", models.DateTimeField()),
                ("sequence", models.IntegerField()),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="bus_app.bus",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="end_stop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="end_bookings",
                to="bus_app.stop",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_stop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="start_bookings",
                to="bus_app.stop",
            ),
        ),
    ]
